# Generated by pg-scaffolding 2025-09-29 09:30:47
from typing import List

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from app.crud import criterion
from app.schemas import criterion as criterion_schema
from app.core.db import SessionLocal

router = APIRouter()

# Dependency
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()



@router.post("/criteria/", response_model=criterion_schema.CriterionCreate)
def create_criteria(criterion_in: criterion_schema.CriterionCreate, db: Session = Depends(get_db)):
    db_obj = criterion.crud.create(db=db, obj_in=criterion_in)
    return db_obj


@router.get("/criteria/", response_model=List[criterion_schema.CriterionRead])
def read_criteria(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    db_obj = criterion.crud.get_multi(db, skip=skip, limit=limit)
    return db_obj


@router.get("/criteria/{criterion_id}", response_model=criterion_schema.CriterionRead)
def read_one_criteria(criterion_id: int, db: Session = Depends(get_db)):
    db_obj = criterion.crud.get(db, id=criterion_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="Criterion not found")
    return db_obj


@router.put("/criteria/{criterion_id}", response_model=criterion_schema.CriterionRead)
def update_criteria(criterion_id: int, criterion_update: criterion_schema.CriterionUpdate, db: Session = Depends(get_db)):
    db_obj = criterion.crud.get(db, id=criterion_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="Criterion not found")
    return criterion.crud.update(db=db, db_obj=db_obj, obj_in=criterion_update)


@router.delete("/criteria/{criterion_id}", response_model=criterion_schema.CriterionRead)
def delete_criteria(criterion_id: int, db: Session = Depends(get_db)):
    db_obj = criterion.crud.get(db, id=criterion_id)
    if db_obj is None:
        raise HTTPException(status_code=404, detail="Criterion not found")
    return criterion.crud.remove(db=db, id=criterion_id)



#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
