# Generated by pg-scaffolding 2025-09-29 09:30:47
from pydantic import BaseModel, EmailStr
from typing import List, Optional
from datetime import datetime, date
from uuid import UUID

from .base import BaseSchema, BaseCreateSchema, BaseReadSchema, BaseUpdateSchema

class AssignmentBase(BaseSchema):
    event_id: int
    submission_id: int
    evaluator_id: int


class AssignmentCreate(AssignmentBase, BaseCreateSchema):
    id: Optional[int] = None

class AssignmentRead(AssignmentBase, BaseReadSchema):
    id: Optional[int] = None
    assigned_at: datetime


class AssignmentUpdate(AssignmentBase, BaseUpdateSchema):
    id: Optional[int] = None
    event_id: Optional[int] = None
    submission_id: Optional[int] = None
    evaluator_id: Optional[int] = None
    assigned_at: Optional[datetime] = None



#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
