# Generated by pg-scaffolding 2025-09-29 09:30:47
from pydantic import BaseModel, EmailStr
from typing import List, Optional
from datetime import datetime, date
from uuid import UUID

from .base import BaseSchema, BaseCreateSchema, BaseReadSchema, BaseUpdateSchema

class CoordinatorBase(BaseSchema):
    event_id: int
    first_name: str
    last_name: str
    email: str
    phone: Optional[str] = None
    title_role: Optional[str] = None
    expertise_description: Optional[str] = None
    affiliation: Optional[str] = None
    status: Optional[str] = None
    accepted_invite_token: Optional[str] = None
    accepted_invite_date: Optional[datetime] = None


class CoordinatorCreate(CoordinatorBase, BaseCreateSchema):
    id: Optional[int] = None

class CoordinatorRead(CoordinatorBase, BaseReadSchema):
    id: Optional[int] = None
    accepted_invite: bool
    created_at: datetime
    updated_at: datetime


class CoordinatorUpdate(CoordinatorBase, BaseUpdateSchema):
    id: Optional[int] = None
    event_id: Optional[int] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    email: Optional[str] = None
    phone: Optional[str] = None
    title_role: Optional[str] = None
    expertise_description: Optional[str] = None
    affiliation: Optional[str] = None
    status: Optional[str] = None
    accepted_invite_token: Optional[str] = None
    accepted_invite_date: Optional[datetime] = None
    accepted_invite: Optional[bool] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None



#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
