# Generated by pg-scaffolding 2025-09-29 09:30:47
from pydantic import BaseModel, EmailStr
from typing import List, Optional
from datetime import datetime, date
from uuid import UUID

from .base import BaseSchema, BaseCreateSchema, BaseReadSchema, BaseUpdateSchema

class CriterionBase(BaseSchema):
    event_id: int
    label: str
    description: str
    category: Optional[str] = None
    sort_pos: int
    value_descriptors: Optional[str] = None


class CriterionCreate(CriterionBase, BaseCreateSchema):
    id: Optional[int] = None

class CriterionRead(CriterionBase, BaseReadSchema):
    id: Optional[int] = None
    required: bool
    weight: float
    max_rating_value: int
    created_at: datetime
    updated_at: datetime


class CriterionUpdate(CriterionBase, BaseUpdateSchema):
    id: Optional[int] = None
    event_id: Optional[int] = None
    label: Optional[str] = None
    description: Optional[str] = None
    category: Optional[str] = None
    required: Optional[bool] = None
    sort_pos: Optional[int] = None
    weight: Optional[float] = None
    max_rating_value: Optional[int] = None
    value_descriptors: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None



#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
