# Generated by pg-scaffolding 2025-09-29 09:30:47
from pydantic import BaseModel, EmailStr
from typing import List, Optional
from datetime import datetime, date
from uuid import UUID

from .base import BaseSchema, BaseCreateSchema, BaseReadSchema, BaseUpdateSchema

class EventBase(BaseSchema):
    user_id: int
    name: str
    description: Optional[str] = None
    event_tz: str
    start_date_time: datetime
    end_date_time: datetime
    location: Optional[str] = None
    affiliation: Optional[str] = None
    logo_path: Optional[str] = None
    max_participants_per_evaluator: int


class EventCreate(EventBase, BaseCreateSchema):
    id: Optional[int] = None

class EventRead(EventBase, BaseReadSchema):
    id: Optional[int] = None
    created_at: datetime


class EventUpdate(EventBase, BaseUpdateSchema):
    id: Optional[int] = None
    user_id: Optional[int] = None
    name: Optional[str] = None
    description: Optional[str] = None
    event_tz: Optional[str] = None
    start_date_time: Optional[datetime] = None
    end_date_time: Optional[datetime] = None
    location: Optional[str] = None
    affiliation: Optional[str] = None
    logo_path: Optional[str] = None
    max_participants_per_evaluator: Optional[int] = None
    created_at: Optional[datetime] = None



#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
