# Generated by pg-scaffolding 2025-09-29 09:30:47
from pydantic import BaseModel, EmailStr
from typing import List, Optional
from datetime import datetime, date
from uuid import UUID

from .base import BaseSchema, BaseCreateSchema, BaseReadSchema, BaseUpdateSchema

class ParticipantBase(BaseSchema):
    event_id: int
    first_name: str
    last_name: str
    email: str
    urgent_contact: Optional[str] = None
    title_role: Optional[str] = None
    affiliation: Optional[str] = None
    additional_contributors: Optional[str] = None


class ParticipantCreate(ParticipantBase, BaseCreateSchema):
    id: Optional[int] = None

class ParticipantRead(ParticipantBase, BaseReadSchema):
    id: Optional[int] = None
    created_at: datetime
    updated_at: datetime


class ParticipantUpdate(ParticipantBase, BaseUpdateSchema):
    id: Optional[int] = None
    event_id: Optional[int] = None
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    email: Optional[str] = None
    urgent_contact: Optional[str] = None
    title_role: Optional[str] = None
    affiliation: Optional[str] = None
    additional_contributors: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None



#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
