# Generated by pg-scaffolding 2025-09-29 09:30:47
from pydantic import BaseModel, EmailStr
from typing import List, Optional
from datetime import datetime, date
from uuid import UUID

from .base import BaseSchema, BaseCreateSchema, BaseReadSchema, BaseUpdateSchema

class SubmissionBase(BaseSchema):
    event_id: int
    participant_id: int
    title: str
    short_description: Optional[str] = None
    description_abstract: str
    submission_category: str
    submission_sub_category: Optional[str] = None
    keywords: Optional[str] = None
    external_link: Optional[str] = None


class SubmissionCreate(SubmissionBase, BaseCreateSchema):
    id: Optional[int] = None

class SubmissionRead(SubmissionBase, BaseReadSchema):
    id: Optional[int] = None
    submission_status: str
    created_at: datetime
    updated_at: datetime


class SubmissionUpdate(SubmissionBase, BaseUpdateSchema):
    id: Optional[int] = None
    event_id: Optional[int] = None
    participant_id: Optional[int] = None
    title: Optional[str] = None
    short_description: Optional[str] = None
    description_abstract: Optional[str] = None
    submission_category: Optional[str] = None
    submission_sub_category: Optional[str] = None
    keywords: Optional[str] = None
    external_link: Optional[str] = None
    submission_status: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None



#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
