# Generated by pg-scaffolding 2025-09-29 09:30:47
from sqlalchemy.orm import Query, joinedload
from app.crud.base import CRUDBase
from app.models.assignment import AssignmentModel
from app.schemas.assignment import AssignmentCreate, AssignmentUpdate



class CRUDAssignment(CRUDBase[AssignmentModel, AssignmentCreate, AssignmentUpdate]):
    """Support simple Create Read Update and Delete (CRUD)"""
    #-- Preserve Custom code START --#
    #-- Preserve Custom code END   --#
    def _apply_get_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Assignment.evaluator),
            joinedload(Assignment.event),
            joinedload(Assignment.submission),
        )

    def _apply_multi_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Assignment.evaluator),
            joinedload(Assignment.event),
            joinedload(Assignment.submission),
            joinedload(Assignment.evaluation),
        )

    def _apply_filter_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Assignment.evaluator),
            joinedload(Assignment.event),
            joinedload(Assignment.submission),
            joinedload(Assignment.evaluation),
        )

crud = CRUDAssignment(AssignmentModel)


#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
