# Generated by pg-scaffolding 2025-09-29 09:30:47
from sqlalchemy.orm import Query, joinedload
from app.crud.base import CRUDBase
from app.models.coordinator import CoordinatorModel
from app.schemas.coordinator import CoordinatorCreate, CoordinatorUpdate



class CRUDCoordinator(CRUDBase[CoordinatorModel, CoordinatorCreate, CoordinatorUpdate]):
    """Support simple Create Read Update and Delete (CRUD)"""
    #-- Preserve Custom code START --#
    #-- Preserve Custom code END   --#
    def _apply_get_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Coordinator.event),
        )

    def _apply_multi_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Coordinator.event),
        )

    def _apply_filter_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Coordinator.event),
        )

crud = CRUDCoordinator(CoordinatorModel)


#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
