# Generated by pg-scaffolding 2025-09-29 09:30:47
from sqlalchemy.orm import Query, joinedload
from app.crud.base import CRUDBase
from app.models.criterion import CriterionModel
from app.schemas.criterion import CriterionCreate, CriterionUpdate



class CRUDCriterion(CRUDBase[CriterionModel, CriterionCreate, CriterionUpdate]):
    """Support simple Create Read Update and Delete (CRUD)"""
    #-- Preserve Custom code START --#
    #-- Preserve Custom code END   --#
    def _apply_get_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Criterion.event),
        )

    def _apply_multi_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Criterion.event),
            joinedload(Criterion.evaluation),
        )

    def _apply_filter_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Criterion.event),
            joinedload(Criterion.evaluation),
        )

crud = CRUDCriterion(CriterionModel)


#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
