# Generated by pg-scaffolding 2025-09-29 09:30:47
from sqlalchemy.orm import Query, joinedload
from app.crud.base import CRUDBase
from app.models.evaluator import EvaluatorModel
from app.schemas.evaluator import EvaluatorCreate, EvaluatorUpdate



class CRUDEvaluator(CRUDBase[EvaluatorModel, EvaluatorCreate, EvaluatorUpdate]):
    """Support simple Create Read Update and Delete (CRUD)"""
    #-- Preserve Custom code START --#
    #-- Preserve Custom code END   --#
    def _apply_get_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Evaluator.event),
        )

    def _apply_multi_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Evaluator.event),
            joinedload(Evaluator.assignment),
        )

    def _apply_filter_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Evaluator.event),
            joinedload(Evaluator.assignment),
        )

crud = CRUDEvaluator(EvaluatorModel)


#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
