# Generated by pg-scaffolding 2025-09-29 09:30:47
from sqlalchemy.orm import Query, joinedload
from app.crud.base import CRUDBase
from app.models.event import EventModel
from app.schemas.event import EventCreate, EventUpdate



class CRUDEvent(CRUDBase[EventModel, EventCreate, EventUpdate]):
    """Support simple Create Read Update and Delete (CRUD)"""
    #-- Preserve Custom code START --#
    #-- Preserve Custom code END   --#
    def _apply_get_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Event.user),
        )

    def _apply_multi_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Event.user),
            joinedload(Event.criteria),
            joinedload(Event.coordinators),
            joinedload(Event.participants),
            joinedload(Event.submissions),
            joinedload(Event.evaluator),
            joinedload(Event.assignments),
        )

    def _apply_filter_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Event.user),
            joinedload(Event.criteria),
            joinedload(Event.coordinators),
            joinedload(Event.participants),
            joinedload(Event.submissions),
            joinedload(Event.evaluator),
            joinedload(Event.assignments),
        )

crud = CRUDEvent(EventModel)


#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
