# Generated by pg-scaffolding 2025-09-29 09:30:47
from sqlalchemy.orm import Query, joinedload
from app.crud.base import CRUDBase
from app.models.participant import ParticipantModel
from app.schemas.participant import ParticipantCreate, ParticipantUpdate



class CRUDParticipant(CRUDBase[ParticipantModel, ParticipantCreate, ParticipantUpdate]):
    """Support simple Create Read Update and Delete (CRUD)"""
    #-- Preserve Custom code START --#
    #-- Preserve Custom code END   --#
    def _apply_get_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Participant.event),
        )

    def _apply_multi_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Participant.event),
            joinedload(Participant.submission),
        )

    def _apply_filter_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Participant.event),
            joinedload(Participant.submission),
        )

crud = CRUDParticipant(ParticipantModel)


#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
