# Generated by pg-scaffolding 2025-09-29 09:30:47
from sqlalchemy.orm import Query, joinedload
from app.crud.base import CRUDBase
from app.models.submission import SubmissionModel
from app.schemas.submission import SubmissionCreate, SubmissionUpdate



class CRUDSubmission(CRUDBase[SubmissionModel, SubmissionCreate, SubmissionUpdate]):
    """Support simple Create Read Update and Delete (CRUD)"""
    #-- Preserve Custom code START --#
    #-- Preserve Custom code END   --#
    def _apply_get_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Submission.event),
            joinedload(Submission.participant),
        )

    def _apply_multi_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Submission.event),
            joinedload(Submission.participant),
            joinedload(Submission.assignment),
        )

    def _apply_filter_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(Submission.event),
            joinedload(Submission.participant),
            joinedload(Submission.assignment),
        )

crud = CRUDSubmission(SubmissionModel)


#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
