# Generated by pg-scaffolding 2025-09-29 09:30:47
from sqlalchemy.orm import Query, joinedload
from app.crud.base import CRUDBase
from app.models.user import UserModel
from app.schemas.user import UserCreate, UserUpdate



class CRUDUser(CRUDBase[UserModel, UserCreate, UserUpdate]):
    """Support simple Create Read Update and Delete (CRUD)"""
    #-- Preserve Custom code START --#
    #-- Preserve Custom code END   --#
    def _apply_get_hook(self, query: Query) -> Query:
        return query.options(
        )

    def _apply_multi_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(User.events),
        )

    def _apply_filter_hook(self, query: Query) -> Query:
        return query.options(
            joinedload(User.events),
        )

crud = CRUDUser(UserModel)


#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
