# Generated by pg-scaffolding 2025-09-29 09:30:47
from __future__ import annotations

from datetime import datetime, date

from sqlalchemy import String, Integer, Float, Boolean, Date, DateTime, TIMESTAMP, UUID, ForeignKey, func, text

from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base

class AssignmentModel(Base):
    __tablename__ = 'assignments'

    id: Mapped[int] = mapped_column(Integer, primary_key=True,  nullable=False)
    event_id: Mapped[int] = mapped_column(Integer, ForeignKey('events.id'), nullable=False)
    submission_id: Mapped[int] = mapped_column(Integer, ForeignKey('submissions.id'),index=True, unique=True,  nullable=False)
    evaluator_id: Mapped[int] = mapped_column(Integer, ForeignKey('evaluators.id'),index=True, unique=True,  nullable=False)
    assigned_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(),  nullable=False)

#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
