# Generated by pg-scaffolding 2025-09-29 09:30:47
from __future__ import annotations

from datetime import datetime, date

from sqlalchemy import String, Integer, Float, Boolean, Date, DateTime, TIMESTAMP, UUID, ForeignKey, func, text

from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base

class ParticipantModel(Base):
    __tablename__ = 'participant'

    id: Mapped[int] = mapped_column(Integer, primary_key=True,  nullable=False)
    event_id: Mapped[int] = mapped_column(Integer, ForeignKey('events.id'), nullable=False)
    first_name: Mapped[str] = mapped_column(String,  nullable=False)
    last_name: Mapped[str] = mapped_column(String,  nullable=False)
    email: Mapped[str] = mapped_column(String,  nullable=False)
    urgent_contact: Mapped[str | None] = mapped_column(String, nullable=True )
    title_role: Mapped[str | None] = mapped_column(String, nullable=True )
    affiliation: Mapped[str | None] = mapped_column(String, nullable=True )
    additional_contributors: Mapped[str | None] = mapped_column(String, nullable=True )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(),  nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(),  nullable=False)

#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
