# Generated by pg-scaffolding 2025-09-29 09:30:47

import os
import logging
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
import debugpy
from app.api.v1 import criterion, assignment, evaluator, submission, event, user, evaluation, submission, participant, participant, coordinator

load_dotenv() 
REACT_APP_URL = os.getenv("REACT_APP_URL", "http://localhost:3000")
API_VERSION_STR = os.getenv("API_VERSION_STR", "/api/v1")


# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

ACTIVATE_DEBUG = os.getenv("ACTIVATE_DEBUG", "FALSE")
if ACTIVATE_DEBUG=="TRUE":
    debugpy.listen(("0.0.0.0", 58979))
    logger.info("Waiting for debugger to attach...")


app = FastAPI(title="Poster Judging App",
              openapi_url=f"{API_VERSION_STR}/openapi.json")

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=[f"{REACT_APP_URL}"],  # Allows frontend to connect
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


app.include_router(criterion.router, prefix=API_VERSION_STR, tags=["criterion"])
app.include_router(assignment.router, prefix=API_VERSION_STR, tags=["assignment"])
app.include_router(evaluator.router, prefix=API_VERSION_STR, tags=["evaluator"])
app.include_router(submission.router, prefix=API_VERSION_STR, tags=["submission"])
app.include_router(event.router, prefix=API_VERSION_STR, tags=["event"])
app.include_router(user.router, prefix=API_VERSION_STR, tags=["user"])
app.include_router(evaluation.router, prefix=API_VERSION_STR, tags=["evaluation"])
app.include_router(submission.router, prefix=API_VERSION_STR, tags=["submission"])
app.include_router(participant.router, prefix=API_VERSION_STR, tags=["participant"])
app.include_router(participant.router, prefix=API_VERSION_STR, tags=["participant"])
app.include_router(coordinator.router, prefix=API_VERSION_STR, tags=["coordinator"])

@app.get("/")
def read_root():
    return {"message": "Welcome to the Fast API Scaffold App"}

    
#-- Preserve Custom code START --#
#-- Preserve Custom code END   --#
